version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100
    reviewers:
      - "Shopify/ruby-dev-exp"
    labels:
      - "dependencies"
      - "ruby"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Shopify/ruby-dev-exp"
    labels:
      - "chore"
      - "dependencies"
      - "gh-actions"
