inherit_gem:
  rubocop-shopify: rubocop.yml

require:
 - rubocop-sorbet
 - rubocop-minitest
 - rubocop-rake

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "test/dummy/db/**/*.rb"

Naming/FileName:
  Exclude:
  - "lib/ruby-lsp-rails.rb"

Sorbet/FalseSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: true
  Include:
    - "test/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "lib/**/*.rb"
    - "test/dummy/**/*.rb"

Sorbet/StrictSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "**/*.rake"
    - "test/**/*.rb"
    - "lib/ruby_lsp/ruby_lsp_rails/server.rb" # we can't assume sorbet-runtime is available
