name: ruby-lsp-rails

nix: true
type: ruby

up:
  - ruby
  - bundler:
      gemfile: Gemfile
  - packages:
      - libyaml

commands:
  style: bin/rubocop
  server:
    aliases: ["s"]
    run: bin/rails server
  typecheck:
    aliases: ["tc"]
    run: "bundle exec srb tc"
  test:
    run: "bin/rails test"
    syntax:
      argument: file
      optional: args...
open:
  app: http://localhost:3000
