# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RailsRubyLsp::ApplicationMailer`.
# Please instead update this file by running `bin/tapioca dsl RailsRubyLsp::ApplicationMailer`.

class RailsRubyLsp::ApplicationMailer; end
