name: Release gem on RubyGems.org and create GitHub release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.beta[0-9]*

jobs:
  release_gem:
    name: Release gem on RubyGems.org
    if: github.repository == 'Shopify/ruby-lsp-rails'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          bundler-cache: true

      - name: Release gem on RubyGems.org
        uses: rubygems/release-gem@052cc82692552de3ef2b81fd670e41d13cba8092 # v1.4.0

  release_github:
    name: Create GitHub release
    if: github.repository == 'Shopify/ruby-lsp-rails'
    needs: release_gem
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.ref }}",
              name: "${{ github.ref_name }}",
              generate_release_notes: true,
              prerelease: "${{ github.ref_name }}".includes(".beta")
            });
